//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanDL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoanDL()
        {
            this.ChiPhis = new HashSet<ChiPhi>();
            this.CTDoans = new HashSet<CTDoan>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> KhoiHanh { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public Nullable<int> LichTrinh { get; set; }
        public Nullable<int> MaTour { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhi> ChiPhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDoan> CTDoans { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
