//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourEntities : DbContext
    {
        public tourEntities()
            : base("name=tourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiPhi> ChiPhis { get; set; }
        public virtual DbSet<CTDoan> CTDoans { get; set; }
        public virtual DbSet<CTTour> CTTours { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<DoanDL> DoanDLs { get; set; }
        public virtual DbSet<Gia> Gias { get; set; }
        public virtual DbSet<LoaiCP> LoaiCPs { get; set; }
        public virtual DbSet<LoaiTour> LoaiTours { get; set; }
        public virtual DbSet<Nguoi> Nguois { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
    }
}
