//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDuLich.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDoan
    {
        internal bool updated = false;

        public int Save()
        {

            if (updated)
            {
                DalCTDoan.Update(this);

            }
            else
            {
                DalCTDoan.Insert(this);

            }

            return 1;
        }
        public void Delete()
        {
            DalCTDoan.Delete(this);
        }
        
    }
}
